package com.dt.afzrms.po;

// Generated 2016-3-12 18:54:09 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * RefUserVehicleGroup generated by hbm2java
 */
@Entity
@Table(name = "REF_USER_VEHICLE_GROUP", catalog = "qdafz")
public class RefUserVehicleGroup implements java.io.Serializable {

	private Integer id;
	private TVehicleGroup TVehicleGroup;
	private TUser TUser;

	public RefUserVehicleGroup() {
	}

	public RefUserVehicleGroup(TVehicleGroup TVehicleGroup, TUser TUser) {
		this.TVehicleGroup = TVehicleGroup;
		this.TUser = TUser;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "vehicleGroupId", nullable = false)
	public TVehicleGroup getTVehicleGroup() {
		return this.TVehicleGroup;
	}

	public void setTVehicleGroup(TVehicleGroup TVehicleGroup) {
		this.TVehicleGroup = TVehicleGroup;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "userId", nullable = false)
	public TUser getTUser() {
		return this.TUser;
	}

	public void setTUser(TUser TUser) {
		this.TUser = TUser;
	}

}
