package com.dt.afzrms.po;

// Generated 2015-1-22 18:06:40 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * RefVehicleGroup generated by hbm2java
 */
@Entity
@Table(name = "REF_VEHICLE_GROUP", catalog = "qdafz")
public class RefVehicleGroup implements java.io.Serializable {

	private Integer id;
	private TVehicleGroup TVehicleGroup;
	private TTerminal TTerminal;

	public RefVehicleGroup() {
	}

	public RefVehicleGroup(TVehicleGroup TVehicleGroup, TTerminal TTerminal) {
		this.TVehicleGroup = TVehicleGroup;
		this.TTerminal = TTerminal;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "vehicle_group_id")
	public TVehicleGroup getTVehicleGroup() {
		return this.TVehicleGroup;
	}

	public void setTVehicleGroup(TVehicleGroup TVehicleGroup) {
		this.TVehicleGroup = TVehicleGroup;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "device_id")
	public TTerminal getTTerminal() {
		return this.TTerminal;
	}

	public void setTTerminal(TTerminal TTerminal) {
		this.TTerminal = TTerminal;
	}

}
