package com.dt.afzrms.po;

// Generated 2015-3-26 10:21:25 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Type;

import com.vividsolutions.jts.geom.Geometry;

/**
 * TAlarmArea generated by hbm2java
 */
@Entity
@Table(name = "T_ALARM_AREA", catalog = "qdafz")
public class TAlarmArea implements java.io.Serializable {

	private Integer id;
	private String name;
	private String description;
	private Geometry xys;
	private Boolean isUsed;
	private String createBy;
	private Date createTime;
	private String remark;
	private Set<RefAlarmruleAreaAlarmarea> refAlarmruleAreaAlarmareas = new HashSet<RefAlarmruleAreaAlarmarea>(0);

	public TAlarmArea() {
	}

	public TAlarmArea(Integer id) {
		this.id = id;
	}

	public TAlarmArea(String name, String description, Geometry xys, Boolean isUsed, String createBy, Date createTime,
			String remark, Set<RefAlarmruleAreaAlarmarea> refAlarmruleAreaAlarmareas) {
		this.name = name;
		this.description = description;
		this.xys = xys;
		this.isUsed = isUsed;
		this.createBy = createBy;
		this.createTime = createTime;
		this.remark = remark;
		this.refAlarmruleAreaAlarmareas = refAlarmruleAreaAlarmareas;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", length = 40)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "description", length = 100)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "xys")
	@Type(type = "org.hibernatespatial.GeometryUserType")
	public Geometry getXys() {
		return this.xys;
	}

	public void setXys(Geometry xys) {
		this.xys = xys;
	}

	@Column(name = "is_used")
	public Boolean getIsUsed() {
		return this.isUsed;
	}

	public void setIsUsed(Boolean isUsed) {
		this.isUsed = isUsed;
	}

	@Column(name = "create_by")
	public String getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_time", length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Column(name = "remark", length = 200)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TAlarmArea")
	public Set<RefAlarmruleAreaAlarmarea> getRefAlarmruleAreaAlarmareas() {
		return refAlarmruleAreaAlarmareas;
	}

	public void setRefAlarmruleAreaAlarmareas(Set<RefAlarmruleAreaAlarmarea> refAlarmruleAreaAlarmareas) {
		this.refAlarmruleAreaAlarmareas = refAlarmruleAreaAlarmareas;
	}

}
