package com.dt.afzrms.po;

// Generated 2015-1-22 18:06:40 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TDept generated by hbm2java
 */
@Entity
@Table(name = "T_DEPT", catalog = "qdafz")
public class TDept implements java.io.Serializable {

	private Integer id;
	private TDept TDept;
	private String name;
	private Integer grade;
	private Integer sortNum;
	private String duty;
	private String director;
	private String createBy;
	private Date createTime;
	private String remark;
	private Set<TTerminal> TTerminals = new HashSet<TTerminal>(0);
	private Set<TRole> TRoles = new HashSet<TRole>(0);
	private Set<TUser> TUsers = new HashSet<TUser>(0);

	public TDept() {
	}

	public TDept(Integer id) {
		this.id = id;
	}

	public TDept(TDept TDept, String name, Integer grade, Integer sortNum,
			String duty, String director, String createBy, Date createTime,
			String remark, Set<TTerminal> TTerminals, Set<TRole> TRoles,
			Set<TUser> TUsers) {
		this.TDept = TDept;
		this.name = name;
		this.grade = grade;
		this.sortNum = sortNum;
		this.duty = duty;
		this.director = director;
		this.createBy = createBy;
		this.createTime = createTime;
		this.remark = remark;
		this.TTerminals = TTerminals;
		this.TRoles = TRoles;
		this.TUsers = TUsers;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "parent_id")
	public TDept getTDept() {
		return this.TDept;
	}

	public void setTDept(TDept TDept) {
		this.TDept = TDept;
	}

	@Column(name = "name", length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "grade")
	public Integer getGrade() {
		return this.grade;
	}

	public void setGrade(Integer grade) {
		this.grade = grade;
	}

	@Column(name = "sort_num")
	public Integer getSortNum() {
		return this.sortNum;
	}

	public void setSortNum(Integer sortNum) {
		this.sortNum = sortNum;
	}

	@Column(name = "duty", length = 100)
	public String getDuty() {
		return this.duty;
	}

	public void setDuty(String duty) {
		this.duty = duty;
	}

	@Column(name = "director", length = 50)
	public String getDirector() {
		return this.director;
	}

	public void setDirector(String director) {
		this.director = director;
	}

	@Column(name = "create_by", length = 50)
	public String getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_time", length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Column(name = "remark", length = 200)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TDept")
	public Set<TTerminal> getTTerminals() {
		return this.TTerminals;
	}

	public void setTTerminals(Set<TTerminal> TTerminals) {
		this.TTerminals = TTerminals;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TDept")
	public Set<TRole> getTRoles() {
		return this.TRoles;
	}

	public void setTRoles(Set<TRole> TRoles) {
		this.TRoles = TRoles;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TDept")
	public Set<TUser> getTUsers() {
		return this.TUsers;
	}

	public void setTUsers(Set<TUser> TUsers) {
		this.TUsers = TUsers;
	}

}
