package com.dt.afzrms.po;

// Generated 2015-1-22 18:06:40 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TModule generated by hbm2java
 */
@Entity
@Table(name = "T_MODULE", catalog = "qdafz")
public class TModule implements java.io.Serializable {

	private Integer id;
	private String name;
	private String description;
	private Integer parentId;
	private Integer grade;
	private Integer sortNum;
	private String urlPath;
	private String jsClassname;
	private Boolean isUsed;
	private Boolean isVisible;
	private Set<RefRoleModule> refRoleModules = new HashSet<RefRoleModule>(0);

	public TModule() {
	}
	
	public TModule(Integer id) {
		this.id = id;
	}

	public TModule(String name, String description, Integer parentId, Integer grade, Integer sortNum, String urlPath,
			String jsClassname, Boolean isUsed, Boolean isVisible, Set<RefRoleModule> refRoleModules) {
		this.name = name;
		this.description = description;
		this.parentId = parentId;
		this.grade = grade;
		this.sortNum = sortNum;
		this.urlPath = urlPath;
		this.jsClassname = jsClassname;
		this.isUsed = isUsed;
		this.isVisible = isVisible;
		this.refRoleModules = refRoleModules;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "description", length = 100)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "parent_id")
	public Integer getParentId() {
		return this.parentId;
	}

	public void setParentId(Integer parentId) {
		this.parentId = parentId;
	}

	@Column(name = "grade")
	public Integer getGrade() {
		return this.grade;
	}

	public void setGrade(Integer grade) {
		this.grade = grade;
	}

	@Column(name = "sort_num")
	public Integer getSortNum() {
		return this.sortNum;
	}

	public void setSortNum(Integer sortNum) {
		this.sortNum = sortNum;
	}

	@Column(name = "url_path", length = 100)
	public String getUrlPath() {
		return this.urlPath;
	}

	public void setUrlPath(String urlPath) {
		this.urlPath = urlPath;
	}
	
	@Column(name = "js_classname", length = 50)
	public String getJsClassname() {
		return jsClassname;
	}

	public void setJsClassname(String jsClassname) {
		this.jsClassname = jsClassname;
	}

	@Column(name = "is_used")
	public Boolean getIsUsed() {
		return this.isUsed;
	}

	public void setIsUsed(Boolean isUsed) {
		this.isUsed = isUsed;
	}

	@Column(name = "is_visible")
	public Boolean getIsVisible() {
		return this.isVisible;
	}

	public void setIsVisible(Boolean isVisible) {
		this.isVisible = isVisible;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TModule")
	public Set<RefRoleModule> getRefRoleModules() {
		return this.refRoleModules;
	}

	public void setRefRoleModules(Set<RefRoleModule> refRoleModules) {
		this.refRoleModules = refRoleModules;
	}

}
