package com.dt.afzrms.po;

// Generated 2015-1-22 18:06:40 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TProtocalType generated by hbm2java
 */
@Entity
@Table(name = "T_PROTOCAL_TYPE", catalog = "qdafz")
public class TProtocalType implements java.io.Serializable {

	private String protocalType;
	private String name;
	private String description;
	private String createBy;
	private Date createTime;
	private Set<TTerminal> TTerminals = new HashSet<TTerminal>(0);

	public TProtocalType() {
	}

	public TProtocalType(String protocalType) {
		this.protocalType = protocalType;
	}

	public TProtocalType(String protocalType, String name, String description, String createBy, Date createTime,
			Set<TTerminal> TTerminals) {
		this.protocalType = protocalType;
		this.name = name;
		this.description = description;
		this.createBy = createBy;
		this.createTime = createTime;
		this.TTerminals = TTerminals;
	}

	@Id
	@Column(name = "protocal_type", unique = true, nullable = false, length = 20)
	public String getProtocalType() {
		return this.protocalType;
	}

	public void setProtocalType(String protocalType) {
		this.protocalType = protocalType;
	}

	@Column(name = "name", length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "description", length = 100)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "create_by", length = 50)
	public String getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_time", length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TProtocalType")
	public Set<TTerminal> getTTerminals() {
		return this.TTerminals;
	}

	public void setTTerminals(Set<TTerminal> TTerminals) {
		this.TTerminals = TTerminals;
	}

}
