package com.dt.afzrms.po;

// Generated 2015-1-22 18:06:40 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * TTerminalAlarmset generated by hbm2java
 */
@Entity
@Table(name = "T_TERMINAL_ALARMSET", catalog = "qdafz")
public class TTerminalAlarmset implements java.io.Serializable {

	private String deviceId;
	private TTerminal TTerminal;
	private Float overspeedThreshold;

	public TTerminalAlarmset() {
	}

	public TTerminalAlarmset(TTerminal TTerminal) {
		this.TTerminal = TTerminal;
	}

	public TTerminalAlarmset(TTerminal TTerminal, Float overspeedThreshold) {
		this.TTerminal = TTerminal;
		this.overspeedThreshold = overspeedThreshold;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "TTerminal"))
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "device_id", unique = true, nullable = false, length = 40)
	public String getDeviceId() {
		return this.deviceId;
	}

	public void setDeviceId(String deviceId) {
		this.deviceId = deviceId;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public TTerminal getTTerminal() {
		return this.TTerminal;
	}

	public void setTTerminal(TTerminal TTerminal) {
		this.TTerminal = TTerminal;
	}

	@Column(name = "overspeed_threshold", precision = 12, scale = 0)
	public Float getOverspeedThreshold() {
		return this.overspeedThreshold;
	}

	public void setOverspeedThreshold(Float overspeedThreshold) {
		this.overspeedThreshold = overspeedThreshold;
	}

}
