package com.dt.afzrms.po;

// Generated 2015-3-31 16:01:17 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * TTjDeptAlarm generated by hbm2java
 */
@Entity
@Table(name = "T_TJ_DEPT_ALARM", catalog = "qdafz")
public class TTjDeptAlarm implements java.io.Serializable {

	private TTjDeptAlarmId id;
	private Integer speedAlarmCount;
	private Integer areaAlarmCount;
	private Integer areaSpeedAlarmCount;

	public TTjDeptAlarm() {
	}

	public TTjDeptAlarm(TTjDeptAlarmId id) {
		this.id = id;
	}

	public TTjDeptAlarm(TTjDeptAlarmId id, Integer speedAlarmCount, Integer areaAlarmCount, Integer areaSpeedAlarmCount) {
		this.id = id;
		this.speedAlarmCount = speedAlarmCount;
		this.areaAlarmCount = areaAlarmCount;
		this.areaSpeedAlarmCount = areaSpeedAlarmCount;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "deptId", column = @Column(name = "dept_id", nullable = false)),
			@AttributeOverride(name = "tjDate", column = @Column(name = "tj_date", nullable = false, length = 10)) })
	public TTjDeptAlarmId getId() {
		return this.id;
	}

	public void setId(TTjDeptAlarmId id) {
		this.id = id;
	}

	@Column(name = "speed_alarm_count")
	public Integer getSpeedAlarmCount() {
		return this.speedAlarmCount;
	}

	public void setSpeedAlarmCount(Integer speedAlarmCount) {
		this.speedAlarmCount = speedAlarmCount;
	}

	@Column(name = "area_alarm_count")
	public Integer getAreaAlarmCount() {
		return this.areaAlarmCount;
	}

	public void setAreaAlarmCount(Integer areaAlarmCount) {
		this.areaAlarmCount = areaAlarmCount;
	}

	@Column(name = "area_speed_alarm_count")
	public Integer getAreaSpeedAlarmCount() {
		return this.areaSpeedAlarmCount;
	}

	public void setAreaSpeedAlarmCount(Integer areaSpeedAlarmCount) {
		this.areaSpeedAlarmCount = areaSpeedAlarmCount;
	}

}
