package com.dt.afzrms.po;

// Generated 2015-3-31 16:01:17 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TTjTermOnoffline generated by hbm2java
 */
@Entity
@Table(name = "T_TJ_TERM_ONOFFLINE", catalog = "qdafz")
public class TTjTermOnoffline implements java.io.Serializable {

	private Date tjDate;
	private Integer onlineCount;
	private Integer offlineCount;
	private Float onlineRate;

	public TTjTermOnoffline() {
	}

	public TTjTermOnoffline(Date tjDate) {
		this.tjDate = tjDate;
	}

	public TTjTermOnoffline(Date tjDate, Integer onlineCount, Integer offlineCount, Float onlineRate) {
		this.tjDate = tjDate;
		this.onlineCount = onlineCount;
		this.offlineCount = offlineCount;
		this.onlineRate = onlineRate;
	}

	@Id
	@Column(name = "tj_date", nullable = false, length = 10)
	public Date getTjDate() {
		return this.tjDate;
	}

	public void setTjDate(Date tjDate) {
		this.tjDate = tjDate;
	}

	@Column(name = "online_count")
	public Integer getOnlineCount() {
		return this.onlineCount;
	}

	public void setOnlineCount(Integer onlineCount) {
		this.onlineCount = onlineCount;
	}

	@Column(name = "offline_count")
	public Integer getOfflineCount() {
		return this.offlineCount;
	}

	public void setOfflineCount(Integer offlineCount) {
		this.offlineCount = offlineCount;
	}

	@Column(name = "online_rate", precision = 12, scale = 0)
	public Float getOnlineRate() {
		return this.onlineRate;
	}

	public void setOnlineRate(Float onlineRate) {
		this.onlineRate = onlineRate;
	}

}
