package com.dt.afzrms.po;

// Generated 2015-3-31 15:28:59 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TTjTermAlarmId generated by hbm2java
 */
@Embeddable
public class TTjTermAlarmId implements java.io.Serializable {

	private String deviceId;
	private Date tjDate;

	public TTjTermAlarmId() {
	}

	public TTjTermAlarmId(String deviceId, Date tjDate) {
		this.deviceId = deviceId;
		this.tjDate = tjDate;
	}

	@Column(name = "device_id", nullable = false, length = 40)
	public String getDeviceId() {
		return this.deviceId;
	}

	public void setDeviceId(String deviceId) {
		this.deviceId = deviceId;
	}

	@Column(name = "tj_date", nullable = false, length = 10)
	public Date getTjDate() {
		return this.tjDate;
	}

	public void setTjDate(Date tjDate) {
		this.tjDate = tjDate;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TTjTermAlarmId))
			return false;
		TTjTermAlarmId castOther = (TTjTermAlarmId) other;

		return ((this.getDeviceId() == castOther.getDeviceId()) || (this.getDeviceId() != null
				&& castOther.getDeviceId() != null && this.getDeviceId().equals(castOther.getDeviceId())))
				&& ((this.getTjDate() == castOther.getTjDate()) || (this.getTjDate() != null
						&& castOther.getTjDate() != null && this.getTjDate().equals(castOther.getTjDate())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getDeviceId() == null ? 0 : this.getDeviceId().hashCode());
		result = 37 * result + (getTjDate() == null ? 0 : this.getTjDate().hashCode());
		return result;
	}

}
