package com.dt.afzrms.po;

// Generated 2015-3-31 16:01:17 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TTjTermOperation generated by hbm2java
 */
@Entity
@Table(name = "T_TJ_TERM_OPERATION", catalog = "qdafz")
public class TTjTermOperation implements java.io.Serializable {

	private TTjTermOperationId id;
	private Integer travelTime;
	private Integer engineRunningTime;
	private Float distance;
	private Float maxSpeed;
	private Float averageSpeed;
	private Date maxSpeedTime;

	public TTjTermOperation() {
	}

	public TTjTermOperation(TTjTermOperationId id) {
		this.id = id;
	}

	public TTjTermOperation(TTjTermOperationId id, Integer travelTime, Integer engineRunningTime, Float distance,
			Float maxSpeed, Float averageSpeed, Date maxSpeedTime) {
		this.id = id;
		this.travelTime = travelTime;
		this.engineRunningTime = engineRunningTime;
		this.distance = distance;
		this.maxSpeed = maxSpeed;
		this.averageSpeed = averageSpeed;
		this.maxSpeedTime = maxSpeedTime;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "deviceId", column = @Column(name = "device_id", nullable = false, length = 40)),
			@AttributeOverride(name = "tjDate", column = @Column(name = "tj_date", nullable = false, length = 10)) })
	public TTjTermOperationId getId() {
		return this.id;
	}

	public void setId(TTjTermOperationId id) {
		this.id = id;
	}

	@Column(name = "travel_time")
	public Integer getTravelTime() {
		return this.travelTime;
	}

	public void setTravelTime(Integer travelTime) {
		this.travelTime = travelTime;
	}

	@Column(name = "engine_running_time")
	public Integer getEngineRunningTime() {
		return this.engineRunningTime;
	}

	public void setEngineRunningTime(Integer engineRunningTime) {
		this.engineRunningTime = engineRunningTime;
	}

	@Column(name = "distance", precision = 12, scale = 0)
	public Float getDistance() {
		return this.distance;
	}

	public void setDistance(Float distance) {
		this.distance = distance;
	}

	@Column(name = "max_speed", precision = 12, scale = 0)
	public Float getMaxSpeed() {
		return this.maxSpeed;
	}

	public void setMaxSpeed(Float maxSpeed) {
		this.maxSpeed = maxSpeed;
	}

	@Column(name = "average_speed", precision = 12, scale = 0)
	public Float getAverageSpeed() {
		return this.averageSpeed;
	}

	public void setAverageSpeed(Float averageSpeed) {
		this.averageSpeed = averageSpeed;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "max_speed_time", length = 19)
	public Date getMaxSpeedTime() {
		return this.maxSpeedTime;
	}

	public void setMaxSpeedTime(Date maxSpeedTime) {
		this.maxSpeedTime = maxSpeedTime;
	}
}
