package com.mapabc.gater.directl.bean.status;

// Generated by MyEclipse Persistence Tools

/**
 * TTermStatusRecord generated by MyEclipse Persistence Tools
 */
public class TTermStatusRecord extends AbstractTTermStatusRecord implements
		java.io.Serializable {

	// Constructors

	/** default constructor */
	public TTermStatusRecord() {
	}
	
	
	
 
}
