package com.mapabc.gater.directl.parse.longhan;

// Generated by MyEclipse Persistence Tools

/**
 * TOilboxCoefficient generated by MyEclipse Persistence Tools
 */
public class TOilboxCoefficient extends AbstractTOilboxCoefficient implements
		java.io.Serializable {

	// Constructors

	/** default constructor */
	public TOilboxCoefficient() {
	}
 

}
