package com.mapabc.gater.lbsgateway.bean;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * AbstractTTerminal generated by MyEclipse - Hibernate Tools
 */

public abstract class AbstractTTerminal implements java.io.Serializable {

	// Fields

	private String deviceId;
	private String TEntTermtype;
	private String termName;
	private String imgUrl;
	private Long suiteId;
	private String entCode;
	private String simcard;
	private String oemCode;
	private String driverNumber;
	private String locateType;
	private Long carTypeId;
	private String isAllocate;
	private String subCompany;
	private Date crtdate;
	private Long usageFlag;
	private Date outdate;
	private boolean isOnline;
	private String gid;
	private String ip;
	private int port;
	private String linkType;
	private String centerId;
	private String centerPwd;
	private String objId;
	private String objType;

	private Set TLocrecords = new HashSet(0);
	private Set TMutiMediums = new HashSet(0);
	private Set TLastLocrecords = new HashSet(0);
	private Set TInactiveAlarmLocs = new HashSet(0);
	private Set refTermGroups = new HashSet(0);
	private Set TStructionses = new HashSet(0);
	private Set TSpeedAlarmLocs = new HashSet(0);
	private Set TAreaLocrecords = new HashSet(0);
	private Set refTermAttrules = new HashSet(0);
	private Set refTermSimrules = new HashSet(0);
	private Set refTermVirgroups = new HashSet(0);

	// Constructors

	public Set getRefTermAttrules() {
		return refTermAttrules;
	}

	public void setRefTermAttrules(Set refTermAttrules) {
		this.refTermAttrules = refTermAttrules;
	}

	public Set getRefTermSimrules() {
		return refTermSimrules;
	}

	public void setRefTermSimrules(Set refTermSimrules) {
		this.refTermSimrules = refTermSimrules;
	}

	/** default constructor */
	public AbstractTTerminal() {
	}

	/** minimal constructor */
	public AbstractTTerminal(String termName) {
		this.termName = termName;
	}

	/** full constructor */
	public AbstractTTerminal(String TEntTermtype, String termName,
			String imgUrl, Long suiteId, String entCode, String simcard,
			String oemCode, String driverNumber, String locateType,
			Long carTypeId, String isAllocate, String subCompany,
			Set TLocrecords, Set TMutiMediums, Set TLastLocrecords,
			Set TInactiveAlarmLocs, Set refTermGroups, Set TStructionses,
			Set TSpeedAlarmLocs, Set TAreaLocrecords, Set refTermAttrules,
			Set refTermSimrules, Set refTermVirgroups) {
		this.TEntTermtype = TEntTermtype;
		this.termName = termName;
		this.imgUrl = imgUrl;
		this.suiteId = suiteId;
		this.entCode = entCode;
		this.simcard = simcard;
		this.oemCode = oemCode;
		this.driverNumber = driverNumber;
		this.locateType = locateType;
		this.carTypeId = carTypeId;
		this.isAllocate = isAllocate;
		this.subCompany = subCompany;
		this.TLocrecords = TLocrecords;
		this.TMutiMediums = TMutiMediums;
		this.TLastLocrecords = TLastLocrecords;
		this.TInactiveAlarmLocs = TInactiveAlarmLocs;
		this.refTermGroups = refTermGroups;
		this.TStructionses = TStructionses;
		this.TSpeedAlarmLocs = TSpeedAlarmLocs;
		this.TAreaLocrecords = TAreaLocrecords;
		this.refTermAttrules = refTermAttrules;
		this.refTermSimrules = refTermSimrules;
		this.refTermVirgroups = refTermVirgroups;
	}

	// Property accessors

	public String getDeviceId() {
		return this.deviceId;
	}

	public void setDeviceId(String deviceId) {
		this.deviceId = deviceId;
	}

	public String getTEntTermtype() {
		return this.TEntTermtype;
	}

	public void setTEntTermtype(String TEntTermtype) {
		this.TEntTermtype = TEntTermtype;
	}

	public String getTermName() {
		return this.termName;
	}

	public void setTermName(String termName) {
		this.termName = termName;
	}

	public String getImgUrl() {
		return this.imgUrl;
	}

	public void setImgUrl(String imgUrl) {
		this.imgUrl = imgUrl;
	}

	public Long getSuiteId() {
		return this.suiteId;
	}

	public void setSuiteId(Long suiteId) {
		this.suiteId = suiteId;
	}

	public String getEntCode() {
		return this.entCode;
	}

	public void setEntCode(String entCode) {
		this.entCode = entCode;
	}

	public String getSimcard() {
		return this.simcard;
	}

	public void setSimcard(String simcard) {
		this.simcard = simcard;
	}

	public Set getTLocrecords() {
		return this.TLocrecords;
	}

	public void setTLocrecords(Set TLocrecords) {
		this.TLocrecords = TLocrecords;
	}

	public Set getTMutiMediums() {
		return this.TMutiMediums;
	}

	public void setTMutiMediums(Set TMutiMediums) {
		this.TMutiMediums = TMutiMediums;
	}

	public Set getTLastLocrecords() {
		return this.TLastLocrecords;
	}

	public void setTLastLocrecords(Set TLastLocrecords) {
		this.TLastLocrecords = TLastLocrecords;
	}

	public Set getTInactiveAlarmLocs() {
		return this.TInactiveAlarmLocs;
	}

	public void setTInactiveAlarmLocs(Set TInactiveAlarmLocs) {
		this.TInactiveAlarmLocs = TInactiveAlarmLocs;
	}

	public Set getRefTermGroups() {
		return this.refTermGroups;
	}

	public void setRefTermGroups(Set refTermGroups) {
		this.refTermGroups = refTermGroups;
	}

	public Set getTStructionses() {
		return this.TStructionses;
	}

	public void setTStructionses(Set TStructionses) {
		this.TStructionses = TStructionses;
	}

	public Set getTSpeedAlarmLocs() {
		return this.TSpeedAlarmLocs;
	}

	public void setTSpeedAlarmLocs(Set TSpeedAlarmLocs) {
		this.TSpeedAlarmLocs = TSpeedAlarmLocs;
	}

	public Set getTAreaLocrecords() {
		return this.TAreaLocrecords;
	}

	public void setTAreaLocrecords(Set TAreaLocrecords) {
		this.TAreaLocrecords = TAreaLocrecords;
	}

	public String getOemCode() {
		return this.oemCode;
	}

	public void setOemCode(String oemCode) {
		this.oemCode = oemCode;
	}

	public String getDriverNumber() {
		return this.driverNumber;
	}

	public void setDriverNumber(String driverNumber) {
		this.driverNumber = driverNumber;
	}

	public String getLocateType() {
		return this.locateType;
	}

	public void setLocateType(String locateType) {
		this.locateType = locateType;
	}

	public Long getCarTypeId() {
		return this.carTypeId;
	}

	public void setCarTypeId(Long carTypeId) {
		this.carTypeId = carTypeId;
	}

	public String getIsAllocate() {
		return this.isAllocate;
	}

	public void setIsAllocate(String isAllocate) {
		this.isAllocate = isAllocate;
	}

	public String getSubCompany() {
		return this.subCompany;
	}

	public void setSubCompany(String subCompany) {
		this.subCompany = subCompany;
	}

	public Date getCrtdate() {
		return crtdate;
	}

	public void setCrtdate(Date crtdate) {
		this.crtdate = crtdate;
	}

	public Long getUsageFlag() {
		return usageFlag;
	}

	public void setUsageFlag(Long usageFlag) {
		this.usageFlag = usageFlag;
	}

	public Date getOutdate() {
		return outdate;
	}

	public void setOutdate(Date outdate) {
		this.outdate = outdate;
	}

	public Set getRefTermVirgroups() {
		return refTermVirgroups;
	}

	public void setRefTermVirgroups(Set refTermVirgroups) {
		this.refTermVirgroups = refTermVirgroups;
	}

	/**
	 * @return the gid
	 */
	public String getGid() {
		return this.gid;
	}

	/**
	 * @param gid
	 *            the gid to set
	 */
	public void setGid(String gid) {
		this.gid = gid;
	}

	/**
	 * @return the isOnline
	 */
	public boolean isOnline() {
		return this.isOnline;
	}

	/**
	 * @param isOnline
	 *            the isOnline to set
	 */
	public void setOnline(boolean isOnline) {
		this.isOnline = isOnline;
	}

	/**
	 * @return the ip
	 */
	public String getIp() {
		return this.ip;
	}

	/**
	 * @return the port
	 */
	public int getPort() {
		return this.port;
	}

	/**
	 * @return the linkType
	 */
	public String getLinkType() {
		return this.linkType;
	}

	/**
	 * @param ip
	 *            the ip to set
	 */
	public void setIp(String ip) {
		this.ip = ip;
	}

	/**
	 * @param port
	 *            the port to set
	 */
	public void setPort(int port) {
		this.port = port;
	}

	/**
	 * @param linkType
	 *            the linkType to set
	 */
	public void setLinkType(String linkType) {
		this.linkType = linkType;
	}

	/**
	 * @return the centerId
	 */
	public String getCenterId() {
		return this.centerId;
	}

	/**
	 * @return the centerPwd
	 */
	public String getCenterPwd() {
		return this.centerPwd;
	}

	/**
	 * @param centerId
	 *            the centerId to set
	 */
	public void setCenterId(String centerId) {
		this.centerId = centerId;
	}

	/**
	 * @param centerPwd
	 *            the centerPwd to set
	 */
	public void setCenterPwd(String centerPwd) {
		this.centerPwd = centerPwd;
	}

	/**
	 * @return the objId
	 */
	public String getObjId() {
		return this.objId;
	}

	/**
	 * @return the objType
	 */
	public String getObjType() {
		return this.objType;
	}

	/**
	 * @param objId
	 *            the objId to set
	 */
	public void setObjId(String objId) {
		this.objId = objId;
	}

	/**
	 * @param objType
	 *            the objType to set
	 */
	public void setObjType(String objType) {
		this.objType = objType;
	}

	@Override
	public String toString() {
		// TODO Auto-generated method stub
		return "deviceid=" + this.deviceId + ",eid=" + this.entCode + ",gid="
				+ this.gid + ",locatetype=" + this.locateType + ",typeCode="
				+ this.TEntTermtype + ",objId=" + this.objId + ",objType="
				+ objType;
	}
}