package com.mapabc.gater.lbsgateway.bean;

import java.util.Date;

/**
 * AbstractTFlowVolume generated by MyEclipse Persistence Tools
 */

public abstract class AbstractTFlowVolume implements java.io.Serializable {

	// Fields

	private Long id;

	private String deviceId;

	private Long flowSize;

	private String actionType;

	private String linkType;

	private Date crtDate;

	// Constructors

	/** default constructor */
	public AbstractTFlowVolume() {
	}

	/** full constructor */
	public AbstractTFlowVolume(String deviceId, Long flowSize,
			String actionType, String linkType, Date crtDate) {
		this.deviceId = deviceId;
		this.flowSize = flowSize;
		this.actionType = actionType;
		this.linkType = linkType;
		this.crtDate = crtDate;
	}

	// Property accessors

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getDeviceId() {
		return this.deviceId;
	}

	public void setDeviceId(String deviceId) {
		this.deviceId = deviceId;
	}

	public Long getFlowSize() {
		return this.flowSize;
	}

	public void setFlowSize(Long flowSize) {
		this.flowSize = flowSize;
	}

	public String getActionType() {
		return this.actionType;
	}

	public void setActionType(String actionType) {
		this.actionType = actionType;
	}

	public String getLinkType() {
		return this.linkType;
	}

	public void setLinkType(String linkType) {
		this.linkType = linkType;
	}

	public Date getCrtDate() {
		return this.crtDate;
	}

	public void setCrtDate(Date crtDate) {
		this.crtDate = crtDate;
	}

}