package com.mapabc.gater.directl.bean.command;

// Generated by MyEclipse Persistence Tools

import java.util.Date;

/**
 * TStructions generated by MyEclipse Persistence Tools
 */
public class TStructions extends AbstractTStructions implements
		java.io.Serializable {

	// Constructors

	/** default constructor */
	public TStructions() {
	}

	/** full constructor */
	public TStructions(String deviceId, String objId, String objType,
			String req, Date receiveTime, String type, String instruction,
			String param, Date sendTime, String sendCount, String reply,
			String state, String descp, String creator, Date createTime) {
		super(deviceId, objId, objType, req, receiveTime, type, instruction,
				param, sendTime, sendCount, reply, state, descp, creator,
				createTime);
	}

}
