package com.dt.afzrms.po;

// Generated 2015-1-22 18:06:40 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TTerminal generated by hbm2java
 */
@Entity
@Table(name = "T_TERMINAL", catalog = "qdafz")
public class TTerminal implements java.io.Serializable {

	private String deviceId;
	private String name;
	private String simcard;
	private Boolean locateType;
	private Boolean isUsed;
	private String createBy;
	private Date createTime;
	private String remark;
	private Integer frequency;
	private Integer deptId;

	public TTerminal() {
	}

	public TTerminal(String deviceId) {
		this.deviceId = deviceId;
	}

	public TTerminal(String deviceId, String name, String simcard, Boolean locateType, Boolean isUsed, String createBy,
			Date createTime, String remark) {
		this.deviceId = deviceId;
		this.name = name;
		this.simcard = simcard;
		this.locateType = locateType;
		this.isUsed = isUsed;
		this.createBy = createBy;
		this.createTime = createTime;
		this.remark = remark;
	}

	@Id
	@Column(name = "device_id", unique = true, nullable = false, length = 40)
	public String getDeviceId() {
		return this.deviceId;
	}

	public void setDeviceId(String deviceId) {
		this.deviceId = deviceId;
	}

	@Column(name = "name", length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "simcard", length = 11)
	public String getSimcard() {
		return this.simcard;
	}

	public void setSimcard(String simcard) {
		this.simcard = simcard;
	}

	@Column(name = "locate_type")
	public Boolean getLocateType() {
		return this.locateType;
	}

	public void setLocateType(Boolean locateType) {
		this.locateType = locateType;
	}

	@Column(name = "is_used")
	public Boolean getIsUsed() {
		return isUsed;
	}

	public void setIsUsed(Boolean isUsed) {
		this.isUsed = isUsed;
	}

	@Column(name = "create_by", length = 50)
	public String getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_time", length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Column(name = "remark", length = 200)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Column(name = "frequency")
	public Integer getFrequency() {
		return frequency;
	}

	public void setFrequency(Integer frequency) {
		this.frequency = frequency;
	}

	@Column(name = "dept_id")
	public Integer getDeptId() {
		return deptId;
	}

	public void setDeptId(Integer deptId) {
		this.deptId = deptId;
	}

}
