package com.dt.afzrms.po;

// Generated 2015-3-31 16:01:17 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TTjDeptAlarmId generated by hbm2java
 */
@Embeddable
public class TTjDeptAlarmId implements java.io.Serializable {

	private Integer deptId;
	private Date tjDate;

	public TTjDeptAlarmId() {
	}

	public TTjDeptAlarmId(Integer deptId, Date tjDate) {
		this.deptId = deptId;
		this.tjDate = tjDate;
	}

	@Column(name = "dept_id", nullable = false)
	public Integer getDeptId() {
		return this.deptId;
	}

	public void setDeptId(Integer deptId) {
		this.deptId = deptId;
	}

	@Column(name = "tj_date", nullable = false, length = 10)
	public Date getTjDate() {
		return this.tjDate;
	}

	public void setTjDate(Date tjDate) {
		this.tjDate = tjDate;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TTjDeptAlarmId))
			return false;
		TTjDeptAlarmId castOther = (TTjDeptAlarmId) other;

		return ((this.getDeptId() == castOther.getDeptId()) || (this.getDeptId() != null
				&& castOther.getDeptId() != null && this.getDeptId().equals(castOther.getDeptId())))
				&& ((this.getTjDate() == castOther.getTjDate()) || (this.getTjDate() != null
						&& castOther.getTjDate() != null && this.getTjDate().equals(castOther.getTjDate())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getDeptId() == null ? 0 : this.getDeptId().hashCode());
		result = 37 * result + (getTjDate() == null ? 0 : this.getTjDate().hashCode());
		return result;
	}

}
