package com.dt.afzrms.po;

// Generated 2015-1-22 18:06:40 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * RefRoleModule generated by hbm2java
 */
@Entity
@Table(name = "REF_ROLE_MODULE", catalog = "qdafz")
public class RefRoleModule implements java.io.Serializable {

	private Integer id;
	private TRole TRole;
	private TModule TModule;

	public RefRoleModule() {
	}

	public RefRoleModule(TRole TRole, TModule TModule) {
		this.TRole = TRole;
		this.TModule = TModule;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "role_id")
	public TRole getTRole() {
		return this.TRole;
	}

	public void setTRole(TRole TRole) {
		this.TRole = TRole;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "module_id")
	public TModule getTModule() {
		return this.TModule;
	}

	public void setTModule(TModule TModule) {
		this.TModule = TModule;
	}

}
