package com.dt.afzrms.po;

// Generated 2015-3-27 10:49:39 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * RefTerminalAlarmruleArea generated by hbm2java
 */
@Entity
@Table(name = "REF_TERMINAL_ALARMRULE_AREA", catalog = "qdafz")
public class RefTerminalAlarmruleArea implements java.io.Serializable {

	private Integer id;
	private TTerminal TTerminal;
	private TAlarmruleArea TAlarmruleArea;

	public RefTerminalAlarmruleArea() {
	}

	public RefTerminalAlarmruleArea(TAlarmruleArea TAlarmruleArea) {
		this.TAlarmruleArea = TAlarmruleArea;
	}

	public RefTerminalAlarmruleArea(TTerminal TTerminal, TAlarmruleArea TAlarmruleArea) {
		this.TTerminal = TTerminal;
		this.TAlarmruleArea = TAlarmruleArea;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "device_id")
	public TTerminal getTTerminal() {
		return this.TTerminal;
	}

	public void setTTerminal(TTerminal TTerminal) {
		this.TTerminal = TTerminal;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "alarmrule_area_id", nullable = false)
	public TAlarmruleArea getTAlarmruleArea() {
		return this.TAlarmruleArea;
	}

	public void setTAlarmruleArea(TAlarmruleArea TAlarmruleArea) {
		this.TAlarmruleArea = TAlarmruleArea;
	}

}
