package com.dt.afzrms.po;

// Generated 2016-9-25 1:17:16 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TMarkers generated by hbm2java
 */
@Entity
@Table(name = "T_MARKERS", catalog = "qdafz")
public class TMarkers implements java.io.Serializable {

	private Integer id;
	private Double x;
	private Double y;
	private String name;
	private Date createTime;
	private Integer userId;
	private int status;
	private String remarker;

	public TMarkers() {
	}

	public TMarkers(int status) {
		this.status = status;
	}

	public TMarkers(Double x, Double y, String name, Date createTime,
			Integer userId, int status, String remarker) {
		this.x = x;
		this.y = y;
		this.name = name;
		this.createTime = createTime;
		this.userId = userId;
		this.status = status;
		this.remarker = remarker;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "x", precision = 12, scale = 7)
	public Double getX() {
		return this.x;
	}

	public void setX(Double x) {
		this.x = x;
	}

	@Column(name = "y", precision = 12, scale = 7)
	public Double getY() {
		return this.y;
	}

	public void setY(Double y) {
		this.y = y;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createTime", length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Column(name = "userId")
	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	@Column(name = "status", nullable = false)
	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	@Column(name = "remarker")
	public String getRemarker() {
		return this.remarker;
	}

	public void setRemarker(String remarker) {
		this.remarker = remarker;
	}

}
