package com.dt.afzrms.po;

// Generated 2015-1-22 18:06:40 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TRole generated by hbm2java
 */
@Entity
@Table(name = "T_ROLE", catalog = "qdafz")
public class TRole implements java.io.Serializable {

	private Integer id;
	private TDept TDept;
	private String name;
	private String description;
	private String createBy;
	private Date createTime;
	private String remark;
	private Boolean roleType;
	private Set<RefRoleModule> refRoleModules = new HashSet<RefRoleModule>(0);
	private Set<RefUserRole> refUserRoles = new HashSet<RefUserRole>(0);

	public TRole() {
	}
	
	public TRole(Integer id) {
		this.id = id;
	}

	public TRole(TDept TDept, String name, String description, String createBy,
			Date createTime, String remark, Boolean roleType,
			Set<RefRoleModule> refRoleModules, Set<RefUserRole> refUserRoles) {
	this.TDept = TDept;
		this.name = name;
		this.description = description;
		this.createBy = createBy;
		this.createTime = createTime;
		this.remark = remark;
		this.roleType = roleType;
		this.refRoleModules = refRoleModules;
		this.refUserRoles = refUserRoles;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "dept_id")
	public TDept getTDept() {
		return this.TDept;
	}

	public void setTDept(TDept TDept) {
		this.TDept = TDept;
	}

	@Column(name = "name", length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "description", length = 100)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "create_by", length = 50)
	public String getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_time", length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Column(name = "remark", length = 200)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}
	
	@Column(name = "role_type")
	public Boolean getRoleType() {
		return roleType;
	}

	public void setRoleType(Boolean roleType) {
		this.roleType = roleType;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TRole")
	public Set<RefRoleModule> getRefRoleModules() {
		return this.refRoleModules;
	}

	public void setRefRoleModules(Set<RefRoleModule> refRoleModules) {
		this.refRoleModules = refRoleModules;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TRole")
	public Set<RefUserRole> getRefUserRoles() {
		return this.refUserRoles;
	}

	public void setRefUserRoles(Set<RefUserRole> refUserRoles) {
		this.refUserRoles = refUserRoles;
	}

}
