package com.dt.afzrms.po;

// Generated 2015-1-22 18:06:40 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TTerminalLoc generated by hbm2java
 */
@Entity
@Table(name = "T_TERMINAL_LOC", catalog = "qdafz")
public class TTerminalLoc implements java.io.Serializable {

	private String deviceId;
	private Float x;
	private Float y;
	private Float speed;
	private Float direction;
	private Float height;
	private Float distance;
	private Date gpsTime;
	private Date inputTime;
	private byte[] deviceStatus;
	private Date onlineTime;
	private Date offlineTime;

	public TTerminalLoc() {
	}

	public TTerminalLoc(String deviceId) {
		this.deviceId = deviceId;
	}

	public TTerminalLoc(String deviceId, Float x, Float y, Float speed, Float direction, Float height, Float distance,
			Date gpsTime, Date inputTime, byte[] deviceStatus, Date onlineTime, Date offlineTime) {
		this.deviceId = deviceId;
		this.x = x;
		this.y = y;
		this.speed = speed;
		this.direction = direction;
		this.height = height;
		this.distance = distance;
		this.gpsTime = gpsTime;
		this.inputTime = inputTime;
		this.deviceStatus = deviceStatus;
		this.onlineTime = onlineTime;
		this.offlineTime = offlineTime;
	}

	@Id
	@Column(name = "device_id", unique = true, nullable = false, length = 40)
	public String getDeviceId() {
		return this.deviceId;
	}

	public void setDeviceId(String deviceId) {
		this.deviceId = deviceId;
	}

	@Column(name = "x", precision = 12, scale = 0)
	public Float getX() {
		return this.x;
	}

	public void setX(Float x) {
		this.x = x;
	}

	@Column(name = "y", precision = 12, scale = 0)
	public Float getY() {
		return this.y;
	}

	public void setY(Float y) {
		this.y = y;
	}

	@Column(name = "speed", precision = 12, scale = 0)
	public Float getSpeed() {
		return this.speed;
	}

	public void setSpeed(Float speed) {
		this.speed = speed;
	}

	@Column(name = "direction", precision = 12, scale = 0)
	public Float getDirection() {
		return this.direction;
	}

	public void setDirection(Float direction) {
		this.direction = direction;
	}

	@Column(name = "height", precision = 12, scale = 0)
	public Float getHeight() {
		return this.height;
	}

	public void setHeight(Float height) {
		this.height = height;
	}

	@Column(name = "distance", precision = 12, scale = 0)
	public Float getDistance() {
		return this.distance;
	}

	public void setDistance(Float distance) {
		this.distance = distance;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "gps_time", length = 19)
	public Date getGpsTime() {
		return this.gpsTime;
	}

	public void setGpsTime(Date gpsTime) {
		this.gpsTime = gpsTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "input_time", length = 19)
	public Date getInputTime() {
		return this.inputTime;
	}

	public void setInputTime(Date inputTime) {
		this.inputTime = inputTime;
	}

	@Column(name = "device_status")
	public byte[] getDeviceStatus() {
		return this.deviceStatus;
	}

	public void setDeviceStatus(byte[] deviceStatus) {
		this.deviceStatus = deviceStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "online_time", length = 19)
	public Date getOnlineTime() {
		return onlineTime;
	}

	public void setOnlineTime(Date onlineTime) {
		this.onlineTime = onlineTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "offline_time", length = 19)
	public Date getOfflineTime() {
		return offlineTime;
	}

	public void setOfflineTime(Date offlineTime) {
		this.offlineTime = offlineTime;
	}

}
