package com.dt.afzrms.po;

// Generated 2016-9-3 22:55:32 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TTerminalDriver generated by hbm2java
 */
@Entity
@Table(name = "T_TERMINAL_DRIVER", catalog = "qdafz")
public class TTerminalDriver implements java.io.Serializable {

	private Integer id;
	private String deviceId;
	private String driverName;
	private String driverSex;
	private String driverPhone;
	private Integer driverage;
	private String driverTime;
	private String driverAddress;
	private String driverLeval;
	private String education;
	private String driverHeight;
	private String remark;

	public TTerminalDriver() {
	}

	public TTerminalDriver(String deviceId, String driverName,
			String driverSex, String driverPhone, Integer driverage,
			String driverTime, String driverAddress, String driverLeval,
			String education, String driverHeight, String remark) {
		this.deviceId = deviceId;
		this.driverName = driverName;
		this.driverSex = driverSex;
		this.driverPhone = driverPhone;
		this.driverage = driverage;
		this.driverTime = driverTime;
		this.driverAddress = driverAddress;
		this.driverLeval = driverLeval;
		this.education = education;
		this.driverHeight = driverHeight;
		this.remark = remark;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "deviceId", length = 244)
	public String getDeviceId() {
		return this.deviceId;
	}

	public void setDeviceId(String deviceId) {
		this.deviceId = deviceId;
	}

	@Column(name = "driverName")
	public String getDriverName() {
		return this.driverName;
	}

	public void setDriverName(String driverName) {
		this.driverName = driverName;
	}

	@Column(name = "driverSex")
	public String getDriverSex() {
		return this.driverSex;
	}

	public void setDriverSex(String driverSex) {
		this.driverSex = driverSex;
	}

	@Column(name = "driverPhone")
	public String getDriverPhone() {
		return this.driverPhone;
	}

	public void setDriverPhone(String driverPhone) {
		this.driverPhone = driverPhone;
	}

	@Column(name = "driverage")
	public Integer getDriverage() {
		return this.driverage;
	}

	public void setDriverage(Integer driverage) {
		this.driverage = driverage;
	}

	@Column(name = "driverTime", length = 3)
	public String getDriverTime() {
		return this.driverTime;
	}

	public void setDriverTime(String driverTime) {
		this.driverTime = driverTime;
	}

	@Column(name = "driverAddress")
	public String getDriverAddress() {
		return this.driverAddress;
	}

	public void setDriverAddress(String driverAddress) {
		this.driverAddress = driverAddress;
	}

	@Column(name = "driverLeval")
	public String getDriverLeval() {
		return this.driverLeval;
	}

	public void setDriverLeval(String driverLeval) {
		this.driverLeval = driverLeval;
	}

	@Column(name = "education")
	public String getEducation() {
		return this.education;
	}

	public void setEducation(String education) {
		this.education = education;
	}

	@Column(name = "driverHeight", length = 22)
	public String getDriverHeight() {
		return this.driverHeight;
	}

	public void setDriverHeight(String driverHeight) {
		this.driverHeight = driverHeight;
	}

	@Column(name = "remark")
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

}
