package com.dt.afzrms.po;

// Generated 2015-3-30 14:05:37 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TTermInstructionRecord generated by hbm2java
 */
@Entity
@Table(name = "T_TERM_INSTRUCTION_RECORD", catalog = "qdafz")
public class TTermInstructionRecord implements java.io.Serializable {

	private Integer id;
	private Date inputTime;
	private Integer instructionType;
	private Integer instructionStatus;
	private String instructionContent;

	public TTermInstructionRecord() {
	}

	public TTermInstructionRecord(Date inputTime, Integer instructionType, Integer instructionStatus,
			String instructionContent) {
		this.inputTime = inputTime;
		this.instructionType = instructionType;
		this.instructionStatus = instructionStatus;
		this.instructionContent = instructionContent;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "input_time", length = 19)
	public Date getInputTime() {
		return this.inputTime;
	}

	public void setInputTime(Date inputTime) {
		this.inputTime = inputTime;
	}

	@Column(name = "instruction_type")
	public Integer getInstructionType() {
		return this.instructionType;
	}

	public void setInstructionType(Integer instructionType) {
		this.instructionType = instructionType;
	}

	@Column(name = "instruction_status")
	public Integer getInstructionStatus() {
		return this.instructionStatus;
	}

	public void setInstructionStatus(Integer instructionStatus) {
		this.instructionStatus = instructionStatus;
	}

	@Column(name = "instruction_content", length = 65535)
	public String getInstructionContent() {
		return this.instructionContent;
	}

	public void setInstructionContent(String instructionContent) {
		this.instructionContent = instructionContent;
	}

}
