package com.dt.afzrms.po;

// Generated 2016-9-3 19:57:48 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TTerminalRepair generated by hbm2java
 */
@Entity
@Table(name = "T_TERMINAL_REPAIR", catalog = "qdafz")
public class TTerminalRepair implements java.io.Serializable {

	private Integer id;
	private String deviceId;
	private String remark;
	private Date createTime;
	private Integer userId;

	public TTerminalRepair() {
	}

	public TTerminalRepair(String deviceId, Date createTime) {
		this.deviceId = deviceId;
		this.createTime = createTime;
	}

	public TTerminalRepair(String deviceId, String remark, Date createTime,
			Integer userId) {
		this.deviceId = deviceId;
		this.remark = remark;
		this.createTime = createTime;
		this.userId = userId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "deviceId", nullable = false)
	public String getDeviceId() {
		return this.deviceId;
	}

	public void setDeviceId(String deviceId) {
		this.deviceId = deviceId;
	}

	@Column(name = "remark")
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createTime", nullable = false, length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Column(name = "userId")
	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

}
